# Generated by Django 4.1.5 on 2023-02-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH PAYMENT', 'CASH PAYMENT'), ('Transfer', 'Transfer'), ('Online Payment', 'Online Payment'), ('Invoice', 'Invoice')], default='Transfer', max_length=100),
            preserve_default=False,
        ),
    ]
