# Generated by Django 4.1.5 on 2023-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_event_schedule_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('ONLINE', 'Online Payment'), ('BANK', 'Bank Transfer'), ('INVOICE', 'Invoice')], max_length=100),
        ),
    ]
