# Generated by Django 4.1.5 on 2023-02-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_booking_options_booking_created_and_more'),
        ('invoice', '0003_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('ONLINE', 'Online Payment'), ('BANK', 'Bank Transfer'), ('INVOICE', 'Invoice')], max_length=100, null=True),
        ),
    ]
