# Generated by Django 4.1.5 on 2023-02-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('REPLIED', 'REPLIED'), ('PENDING', 'PENDING'), ('SETTLED', 'SETTLED')], default='REPLIED', max_length=100),
            preserve_default=False,
        ),
    ]
