# Generated by Django 4.1.5 on 2023-01-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking_has_paid_booking_reference_id_room_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
