# Generated by Django 4.1.5 on 2023-01-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_delete_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='default_exit_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_entry_time',
            field=models.TimeField(null=True),
        ),
    ]
