# Generated by Django 4.1.5 on 2023-12-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_roomtype_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'room_type')},
        ),
    ]
