# Generated by Django 4.1.5 on 2023-02-18 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_booking_options_booking_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 19, 50, 27, 315518, tzinfo=datetime.timezone.utc)),
        ),
    ]
