# Generated by Django 4.1.5 on 2023-02-18 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
